# Appends additional POIs into build.py-generated JSON (runs after build.py)
import json, math
def P(slug, ar, en, lat, lng, prox, q, poi, typ, intents=None, metro=None, kw=None, event=None):
    d = dict(slug=slug, name_ar=ar, name_en=en, lat=lat, lng=lng, prox_km=prox, q=q, poi_label=poi, type=typ,
             intents=intents or ["family","apartments","5-star"], nearest_metro=metro, keywords=kw or [])
    if event: d["event"]=event
    return d
M=["family","medical","apartments"]; S=["family","shopping","apartments"]; B=["budget","family","apartments"]
ADD = {
"riyadh":[
 P("granada-mall","غرناطة مول","Granada Mall",24.7725,46.7380,3,"غرناطة مول","غرناطة مول","landmark",S,kw=["فنادق قريبة من غرناطة مول"]),
 P("riyadh-gallery","الرياض جاليري","Riyadh Gallery",24.7700,46.6640,3,"الرياض جاليري","الرياض جاليري","landmark",S),
 P("centria-mall","سنتريا مول","Centria Mall",24.6930,46.6860,2,"سنتريا مول","سنتريا مول","landmark",S,metro="محطة العليا"),
 P("nakheel-mall","النخيل مول","Al Nakheel Mall",24.7850,46.6590,3,"النخيل مول","النخيل مول","landmark",S),
 P("kfsh","مستشفى الملك فيصل التخصصي","KFSH&RC",24.6780,46.6700,3,"مستشفى الملك فيصل التخصصي","مستشفى التخصصي","hospital",M,kw=["فنادق قريبة من مستشفى الملك فيصل التخصصي","شقق فندقية قريبة من التخصصي"]),
 P("kfmc","مدينة الملك فهد الطبية","King Fahad Medical City",24.6880,46.7060,3,"مدينة الملك فهد الطبية","مدينة الملك فهد الطبية","hospital",M),
 P("kingdom-arena","المملكة أرينا","Kingdom Arena",24.8150,46.6860,5,"المملكة أرينا","المملكة أرينا","stadium",["family","budget"],kw=["فنادق قريبة من المملكة أرينا"]),
 P("king-fahd-stadium","استاد الملك فهد","King Fahd Stadium",24.7640,46.8440,6,"استاد الملك فهد","استاد الملك فهد","stadium",["budget","family"]),
 P("riyadh-train-station","محطة قطار الرياض","Riyadh Train Station (SAR)",24.7090,46.7330,3,"محطة قطار الرياض","محطة القطار","transport",["transit","budget"]),
 P("riyadh-exhibition-center","مركز الرياض الدولي للمعارض","RICEC",24.7750,46.7190,4,"مركز الرياض الدولي للمؤتمرات والمعارض","مركز المعارض","landmark",["corporate","5-star"],kw=["فنادق قريبة من مركز الرياض للمعارض"]),
 P("al-rabie","الربيع","Al Rabie",24.8240,46.6480,4,"الربيع","الربيع","district",B),
 P("al-sahafa","الصحافة","Al Sahafa",24.8100,46.6410,3,"الصحافة","الصحافة","district",B),
 P("al-narjis","النرجس","Al Narjis",24.8480,46.6480,4,"النرجس","النرجس","district",B),
 P("al-yasmin","الياسمين","Al Yasmin",24.8300,46.6800,4,"الياسمين","الياسمين","district",B),
 P("al-sulimaniyah","السليمانية","Al Sulimaniyah",24.7060,46.7020,3,"السليمانية","السليمانية","district",B),
 P("al-wurud","الورود","Al Wurud",24.7260,46.6720,3,"الورود","الورود","district",B),
 P("king-abdullah-park","حديقة الملك عبدالله","King Abdullah Park",24.6810,46.7310,3,"حديقة الملك عبدالله","حديقة الملك عبدالله","landmark",["family","budget"]),
],
"makkah":[
 P("clock-tower","برج الساعة","Makkah Clock Tower",21.4187,39.8256,0.8,"برج الساعة","برج الساعة","landmark",["5-star","haram-view"],kw=["فنادق برج الساعة مكة","فنادق قريبة من برج الساعة"]),
 P("central-area","المنطقة المركزية","Central Area",21.4205,39.8240,1,"المنطقة المركزية مكة","المنطقة المركزية","district",["5-star","family","haram-view"]),
 P("al-rusaifah","الرصيفة","Al Rusaifah",21.4030,39.8000,3,"الرصيفة","الرصيفة","district",B),
 P("al-naseem","النسيم","Al Naseem",21.3900,39.8770,3,"النسيم","النسيم","district",B),
 P("al-kakiyah","الكعكية","Al Kakiyah",21.3740,39.8210,3,"الكعكية","الكعكية","district",B),
 P("al-hijrah","الهجرة","Al Hijrah",21.4190,39.7830,3,"الهجرة","الهجرة","district",B),
 P("al-maabdah","المعابدة","Al Maabdah",21.4370,39.8440,2,"المعابدة","المعابدة","district",B),
 P("al-awali","العوالي","Al Awali",21.3900,39.8200,3,"العوالي","العوالي","district",B),
 P("al-zahir","الزاهر","Al Zahir",21.4330,39.8100,2,"الزاهر","الزاهر","district",B),
 P("jabal-al-nour","جبل النور","Jabal Al Nour",21.4580,39.8600,3,"جبل النور","جبل النور","landmark",["budget","family"],kw=["فنادق قريبة من جبل النور غار حراء"]),
 P("jabal-thawr","جبل ثور","Jabal Thawr",21.3780,39.8480,4,"جبل ثور","جبل ثور","landmark",["budget"]),
 P("aisha-mosque","مسجد عائشة - التنعيم","Aisha Mosque (Tan'eem)",21.4800,39.8060,3,"مسجد عائشة التنعيم","مسجد عائشة","landmark",["budget","family"],kw=["فنادق قريبة من مسجد عائشة التنعيم"]),
 P("al-noor-hospital","مستشفى النور","Al Noor Hospital",21.4080,39.8690,3,"مستشفى النور التخصصي","مستشفى النور","hospital",M),
 P("hajj-2027","فنادق مكة حج 2027","Makkah Hajj 2027",21.4225,39.8262,3,"الحرم المكي","الحرم","event",["family","haram-view"],kw=["فنادق مكة حج 2027","حجز فنادق الحج"],event=dict(start="2027-05-14",end="2027-05-22",note="تقريبي")),
],
"madinah":[
 P("haram-nabawi","الحرم النبوي","Al Haram Al Nabawi",24.4672,39.6112,1,"الحرم النبوي","الحرم النبوي","landmark",["family","haram-view","5-star"],kw=["فنادق قريبة من الحرم النبوي","فنادق الحرم المدينة"]),
 P("rashid-mall","الراشد مول","Al Rashid Mega Mall",24.4750,39.6340,3,"الراشد مول","الراشد مول","landmark",S),
 P("al-aliya-mall","العالية مول","Aliyah Mall",24.4490,39.6160,3,"العالية مول","العالية مول","landmark",S),
 P("al-aziziyah","العزيزية","Al Aziziyah",24.4580,39.6380,3,"العزيزية المدينة","العزيزية","district",B),
 P("sultanah","سلطانة","Sultanah",24.4590,39.5980,2,"سلطانة","سلطانة","district",B),
 P("al-khalidiyah","الخالدية","Al Khalidiyah",24.4780,39.5900,3,"الخالدية","الخالدية","district",B),
 P("seven-mosques","المساجد السبعة","Seven Mosques",24.4770,39.5990,2,"المساجد السبعة","المساجد السبعة","landmark",["budget","family"]),
 P("baqi","البقيع","Al Baqi",24.4670,39.6150,1,"البقيع","البقيع","landmark",["family","haram-view"]),
 P("taibah-university","جامعة طيبة","Taibah University",24.4830,39.5470,4,"جامعة طيبة","جامعة طيبة","landmark",["budget","apartments"]),
 P("king-fahd-hospital","مستشفى الملك فهد","King Fahd Hospital Madinah",24.4830,39.5820,3,"مستشفى الملك فهد المدينة","مستشفى الملك فهد","hospital",M),
],
"dubai":[
 P("mall-of-the-emirates","مول الإمارات","Mall of the Emirates",25.1181,55.2005,2,"مول الامارات","مول الإمارات","landmark",S,metro="مول الإمارات",kw=["فنادق قريبة من مول الامارات","فنادق متصلة بمول الامارات"]),
 P("dubai-festival-city","دبي فستيفال سيتي","Dubai Festival City",25.2220,55.3520,3,"دبي فستيفال سيتي","فستيفال سيتي","landmark",S),
 P("dubai-hills-mall","دبي هيلز مول","Dubai Hills Mall",25.1000,55.2430,3,"دبي هيلز مول","دبي هيلز","landmark",S),
 P("city-walk","سيتي ووك","City Walk",25.2060,55.2620,2,"سيتي ووك","سيتي ووك","landmark",["5-star","family","apartments"]),
 P("city-centre-deira","سيتي سنتر ديرة","City Centre Deira",25.2520,55.3330,2,"سيتي سنتر ديرة","سيتي سنتر ديرة","landmark",S,metro="سيتي سنتر ديرة"),
 P("outlet-village","ذا أوتلت فيليدج","The Outlet Village",25.0600,55.1780,4,"اوتلت فيليدج","الأوتلت فيليدج","landmark",S),
 P("dubai-parks","دبي باركس آند ريزورتس","Dubai Parks and Resorts",24.9200,55.0060,6,"دبي باركس","دبي باركس","landmark",["family"],kw=["فنادق قريبة من دبي باركس","فنادق قريبة من موشن جيت"]),
 P("img-worlds","آي إم جي","IMG Worlds of Adventure",25.0870,55.3280,5,"اي ام جي","IMG","landmark",["family"]),
 P("dubai-frame","برواز دبي","Dubai Frame",25.2350,55.3000,2,"برواز دبي","برواز دبي","landmark",["family","budget"]),
 P("museum-of-the-future","متحف المستقبل","Museum of the Future",25.2190,55.2810,2,"متحف المستقبل","متحف المستقبل","landmark",["5-star","family"],metro="الإمارات تاورز"),
 P("miracle-garden","حديقة الزهور","Miracle Garden",25.0600,55.2440,5,"ميراكل جاردن","حديقة الزهور","landmark",["family","budget"],event=dict(start="2026-11-01",end="2027-05-01",note="موسم الحديقة تقريبي")),
 P("la-mer","لامير","La Mer",25.2280,55.2640,2,"لامير","لامير","landmark",["beach","family","5-star"]),
 P("bluewaters","بلو ووترز - عين دبي","Bluewaters / Ain Dubai",25.0790,55.1230,2,"بلو ووترز","بلو ووترز","landmark",["5-star","family","beach"],kw=["فنادق قريبة من عين دبي"]),
 P("al-qusais","القصيص","Al Qusais",25.2800,55.3800,3,"القصيص","القصيص","district",B,metro="القصيص"),
 P("al-mamzar","الممزر","Al Mamzar",25.2980,55.3470,3,"الممزر","الممزر","district",["family","beach","apartments"]),
 P("al-karama","الكرامة","Al Karama",25.2430,55.3030,2,"الكرامة","الكرامة","district",B,metro="ADCB"),
 P("oud-metha","عود ميثاء","Oud Metha",25.2360,55.3100,2,"عود ميثاء","عود ميثاء","district",B,metro="عود ميثاء"),
 P("al-satwa","السطوة","Al Satwa",25.2250,55.2740,2,"السطوة","السطوة","district",B),
 P("jumeirah-beach","شاطئ جميرا","Jumeirah Beach",25.1930,55.2330,3,"شاطئ جميرا","شاطئ جميرا","landmark",["beach","family"]),
 P("expo-city","إكسبو سيتي","Expo City Dubai",24.9620,55.1510,6,"اكسبو سيتي","إكسبو سيتي","landmark",["family","corporate"]),
 P("burj-al-arab","برج العرب","Burj Al Arab",25.1412,55.1853,3,"برج العرب","برج العرب","landmark",["5-star","beach","couples"],kw=["فنادق قريبة من برج العرب"]),
 P("dubai-sports-city","مدينة دبي الرياضية","Dubai Sports City",25.0430,55.2200,4,"مدينة دبي الرياضية","دبي الرياضية","district",B),
 P("coca-cola-arena","كوكاكولا أرينا","Coca-Cola Arena",25.2060,55.2600,2,"كوكاكولا ارينا","كوكاكولا أرينا","stadium",["family","budget"]),
 P("al-jalila-hospital","مستشفى الجليلة","Al Jalila Hospital",25.2330,55.3200,3,"مستشفى الجليلة","مستشفى الجليلة","hospital",M),
 P("saudi-german-hospital","المستشفى السعودي الألماني","Saudi German Hospital",25.1130,55.2050,3,"المستشفى السعودي الالماني دبي","السعودي الألماني","hospital",M),
],
"istanbul":[
 P("cevahir-mall","جواهر مول","Cevahir Mall",41.0630,28.9920,2,"جواهر مول","جواهر مول","landmark",S,metro="شيشلي-محيدار كوي",kw=["فنادق قريبة من جواهر مول"]),
 P("mall-of-istanbul","مول أوف إسطنبول","Mall of Istanbul",41.0640,28.8060,4,"مول اوف اسطنبول","مول أوف إسطنبول","landmark",S),
 P("zorlu-center","زورلو سنتر","Zorlu Center",41.0670,29.0170,2,"زورلو سنتر","زورلو سنتر","landmark",["5-star","shopping"]),
 P("emaar-square","إعمار سكوير","Emaar Square Mall",40.9990,29.0700,4,"اعمار سكوير","إعمار سكوير","landmark",S),
 P("akmerkez","أكمركز","Akmerkez",41.0770,29.0210,2,"اكمركز","أكمركز","landmark",S),
 P("forum-istanbul","فوروم إسطنبول","Forum Istanbul",41.0460,28.8960,3,"فوروم اسطنبول","فوروم إسطنبول","landmark",S),
 P("eyup","السلطان أيوب","Eyup",41.0480,28.9340,3,"السلطان ايوب","السلطان أيوب","district",B),
 P("karakoy","كاراكوي","Karakoy",41.0230,28.9770,1.5,"كاراكوي","كاراكوي","district",["couples","5-star"]),
 P("ortakoy","أورتاكوي","Ortakoy",41.0480,29.0260,2,"اورتاكوي","أورتاكوي","district",["couples","bosphorus-view"]),
 P("sirkeci","سيركجي","Sirkeci",41.0150,28.9770,1.5,"سيركجي","سيركجي","district",B),
 P("mecidiyekoy","مجيدية كوي","Mecidiyekoy",41.0660,28.9930,2,"مجيدية كوي","مجيدية كوي","district",B,metro="مجيدية كوي"),
 P("esenyurt","إسنيورت","Esenyurt",41.0340,28.6800,5,"اسنيورت","إسنيورت","district",B),
 P("basaksehir","بشاك شهير","Basaksehir",41.0930,28.8020,5,"بشاك شهير","بشاك شهير","district",["family","apartments"]),
 P("beylikduzu","بيليك دوزو","Beylikduzu",41.0030,28.6420,5,"بيليك دوزو","بيليك دوزو","district",["family","apartments"]),
 P("beyoglu","بيوغلو","Beyoglu",41.0320,28.9770,2,"بيوغلو","بيوغلو","district",["couples","budget"]),
 P("hagia-sophia","آيا صوفيا","Hagia Sophia",41.0086,28.9802,1.5,"ايا صوفيا","آيا صوفيا","landmark",["family","couples"],kw=["فنادق قريبة من ايا صوفيا"]),
 P("grand-bazaar","البازار الكبير","Grand Bazaar",41.0108,28.9680,1.5,"البازار الكبير","البازار الكبير","landmark",S),
 P("spice-bazaar","السوق المصري","Spice Bazaar",41.0166,28.9704,1.5,"السوق المصري","السوق المصري","landmark",S),
 P("topkapi-palace","قصر توبكابي","Topkapi Palace",41.0115,28.9833,1.5,"قصر توبكابي","توبكابي","landmark"),
 P("princes-islands","جزر الأميرات","Princes' Islands",40.8760,29.1270,5,"جزر الاميرات","جزر الأميرات","landmark",["couples","family"]),
 P("acibadem-hospital","مستشفى آجيبادم","Acibadem Hospital",41.0160,29.0430,3,"مستشفى اجيبادم","آجيبادم","hospital",M,kw=["فنادق قريبة من مستشفى اجيبادم"]),
 P("memorial-hospital","مستشفى ميموريال","Memorial Sisli Hospital",41.0700,28.9880,3,"مستشفى ميموريال","ميموريال","hospital",M),
],
"rome":[
 P("via-veneto","فيا فينيتو","Via Veneto",41.9075,12.4890,1,"فيا فينيتو","فيا فينيتو","landmark",["5-star","couples"]),
 P("piazza-venezia","ساحة فينيسيا","Piazza Venezia",41.8960,12.4826,1,"ساحة فينيسيا","ساحة فينيسيا","landmark"),
 P("castel-sant-angelo","قلعة سانت أنجلو","Castel Sant'Angelo",41.9031,12.4663,1,"قلعة سانت انجلو","سانت أنجلو","landmark"),
 P("villa-borghese","فيلا بورغيزي","Villa Borghese",41.9140,12.4920,1.5,"فيلا بورغيزي","فيلا بورغيزي","landmark",["family","5-star"]),
 P("monti","مونتي","Monti",41.8950,12.4900,1,"مونتي","مونتي","district",["couples","budget"]),
 P("esquilino","إسكويلينو","Esquilino",41.8960,12.5020,1.5,"اسكويلينو","إسكويلينو","district",B),
 P("campo-de-fiori","كامبو دي فيوري","Campo de' Fiori",41.8955,12.4722,1,"كامبو دي فيوري","كامبو دي فيوري","landmark",["couples"]),
 P("castel-romano-outlet","أوتلت كاستل رومانو","Castel Romano Designer Outlet",41.7180,12.4330,8,"كاستل رومانو اوتلت","أوتلت كاستل رومانو","landmark",S),
 P("st-peters","كاتدرائية القديس بطرس","St. Peter's Basilica",41.9022,12.4539,1,"القديس بطرس","القديس بطرس","landmark"),
 P("piazza-del-popolo","ساحة ديل بوبولو","Piazza del Popolo",41.9107,12.4764,1,"ساحة ديل بوبولو","ديل بوبولو","landmark",["5-star","shopping"]),
],
"bali":[
 P("tanah-lot","معبد تاناه لوت","Tanah Lot",-8.6212,115.0868,6,"تاناه لوت","تاناه لوت","landmark",["couples","villa"]),
 P("uluwatu-temple","معبد أولواتو","Uluwatu Temple",-8.8291,115.0849,4,"معبد اولواتو","معبد أولواتو","landmark",["5-star","couples"]),
 P("tegenungan-waterfall","شلال تيجينونجان","Tegenungan Waterfall",-8.5755,115.2889,6,"شلال تيجينونجان","تيجينونجان","landmark",["nature","villa"]),
 P("tegalalang","مدرجات أرز تيجالالانج","Tegalalang Rice Terrace",-8.4312,115.2790,6,"تيجالالانج","تيجالالانج","landmark",["nature","villa","couples"]),
 P("monkey-forest","غابة القرود أوبود","Ubud Monkey Forest",-8.5188,115.2588,3,"غابة القرود","غابة القرود","landmark",["family","nature"]),
 P("melasti-beach","شاطئ ملاستي","Melasti Beach",-8.8480,115.1580,4,"شاطئ ملاستي","ملاستي","landmark",["beach","couples"]),
 P("nusa-penida","نوسا بينيدا","Nusa Penida",-8.7275,115.5444,10,"نوسا بينيدا","نوسا بينيدا","district",["nature","budget"]),
 P("pererenan","بيريرينان","Pererenan",-8.6380,115.1240,3,"بيريرينان","بيريرينان","district",["villa","couples"]),
 P("padang-padang","شاطئ بادانج بادانج","Padang Padang Beach",-8.8110,115.1040,4,"بادانج بادانج","بادانج بادانج","landmark",["beach","villa"]),
 P("keramas","كيراماس","Keramas",-8.5880,115.3350,5,"كيراماس","كيراماس","district",["villa","5-star","couples"]),
 P("benoa","بينوا","Benoa",-8.7600,115.2200,4,"بينوا","بينوا","district",["family","beach"]),
 P("family","فنادق بالي للعوائل","Bali for families",-8.8000,115.2300,30,"بالي","بالي","intent_hub",["family","5-star"],kw=["فنادق بالي للعوائل","منتجعات بالي للعوائل"]),
 P("private-pool","فنادق بالي مع مسبح خاص","Bali private pool",-8.6913,115.1682,30,"بالي","بالي","intent_hub",["villa","couples","5-star"],kw=["فنادق بالي مع مسبح خاص","فلل بالي مسبح خاص"]),
],
"london":[
 P("marble-arch","ماربل آرش","Marble Arch",51.5131,-0.1589,1.5,"ماربل ارش","ماربل آرش","landmark",["family","apartments"],metro="Marble Arch"),
 P("westfield-white-city","وستفيلد لندن","Westfield London",51.5070,-0.2210,2,"وستفيلد لندن","وستفيلد","landmark",S,metro="Shepherd's Bush"),
 P("westfield-stratford","وستفيلد ستراتفورد","Westfield Stratford",51.5430,-0.0080,2,"وستفيلد ستراتفورد","وستفيلد ستراتفورد","landmark",S,metro="Stratford"),
 P("regent-street","ريجنت ستريت","Regent Street",51.5120,-0.1400,1,"ريجنت ستريت","ريجنت ستريت","landmark",S),
 P("leicester-square","ليستر سكوير","Leicester Square",51.5103,-0.1301,1,"ليستر سكوير","ليستر سكوير","landmark",["family","5-star"],metro="Leicester Square"),
 P("covent-garden","كوفنت غاردن","Covent Garden",51.5120,-0.1230,1,"كوفنت غاردن","كوفنت غاردن","landmark",["couples","shopping"]),
 P("kings-cross","كينغز كروس","King's Cross",51.5308,-0.1238,1.5,"كينغز كروس","كينغز كروس","transport",["transit","budget","family"],metro="King's Cross"),
 P("victoria","فيكتوريا","Victoria",51.4952,-0.1441,1.5,"فيكتوريا","فيكتوريا","transport",["transit","family","budget"],metro="Victoria"),
 P("notting-hill","نوتنغ هيل","Notting Hill",51.5090,-0.1960,1.5,"نوتنغ هيل","نوتنغ هيل","district",["couples","apartments"]),
 P("south-kensington","ساوث كنسينغتون","South Kensington",51.4941,-0.1740,1.5,"ساوث كنسينغتون","ساوث كنسينغتون","district",["family","5-star"],metro="South Kensington"),
 P("chelsea","تشيلسي","Chelsea",51.4875,-0.1687,1.5,"تشيلسي","تشيلسي","district",["5-star","couples"]),
 P("mayfair","مايفير","Mayfair",51.5100,-0.1480,1,"مايفير","مايفير","district",["5-star","couples"]),
 P("piccadilly","بيكاديلي","Piccadilly",51.5098,-0.1342,1,"بيكاديلي","بيكاديلي","landmark",["5-star","family"],metro="Piccadilly Circus"),
 P("harley-street","هارلي ستريت","Harley Street",51.5200,-0.1470,1.5,"هارلي ستريت","هارلي ستريت","hospital",M,kw=["فنادق قريبة من هارلي ستريت","فنادق لندن للعلاج"]),
 P("regents-park","ريجنتس بارك","Regent's Park",51.5313,-0.1570,2,"ريجنتس بارك","ريجنتس بارك","landmark",["family","apartments"]),
 P("gatwick","مطار غاتويك","Gatwick",51.1537,-0.1821,5,"غاتويك","غاتويك","airport",["transit","budget"]),
 P("stamford-bridge","ستامفورد بريدج","Stamford Bridge",51.4817,-0.1910,2,"ستامفورد بريدج","ستامفورد بريدج","stadium",["budget","family"]),
 P("emirates-stadium","ملعب الإمارات","Emirates Stadium",51.5549,-0.1084,2,"ملعب الامارات","ملعب الإمارات","stadium",["budget","family"]),
],
"paris":[
 P("la-vallee-village","لا فالي فيلاج","La Vallee Village",48.8550,2.7780,6,"لا فالي فيلاج","لا فالي فيلاج","landmark",S),
 P("le-marais","لو ماريه","Le Marais",48.8590,2.3620,1.5,"لو ماريه","لو ماريه","district",["couples","apartments"]),
 P("place-vendome","بلاس فاندوم","Place Vendome",48.8675,2.3295,1,"بلاس فاندوم","فاندوم","landmark",["5-star","shopping"]),
 P("bastille","الباستيل","Bastille",48.8532,2.3692,1.5,"الباستيل","الباستيل","district",B),
 P("montparnasse","مونبارناس","Montparnasse",48.8422,2.3210,1.5,"مونبارناس","مونبارناس","transport",["transit","budget","family"]),
 P("trocadero","تروكاديرو","Trocadero",48.8620,2.2875,1,"تروكاديرو","تروكاديرو","landmark",["5-star","couples"],kw=["فنادق مطلة على برج ايفل تروكاديرو"]),
 P("versailles","قصر فرساي","Versailles",48.8049,2.1204,5,"فرساي","فرساي","landmark",["family","couples"]),
 P("rue-de-rivoli","شارع ريفولي","Rue de Rivoli",48.8610,2.3420,1,"شارع ريفولي","ريفولي","landmark",S),
 P("american-hospital","المستشفى الأميركي","American Hospital of Paris",48.8880,2.2600,3,"المستشفى الامريكي باريس","المستشفى الأميركي","hospital",M),
 P("gare-du-nord","محطة الشمال","Gare du Nord",48.8809,2.3553,1.5,"محطة الشمال","محطة الشمال","transport",["transit","budget"]),
],
"milan":[
 P("fidenza-village","فيدينزا فيلاج","Fidenza Village",44.8680,10.0500,10,"فيدينزا فيلاج","فيدينزا","landmark",S),
 P("corso-buenos-aires","كورسو بوينس آيرس","Corso Buenos Aires",45.4780,9.2100,1.5,"كورسو بوينس ايرس","كورسو بوينس آيرس","landmark",S),
 P("brera","بريرا","Brera",45.4720,9.1870,1,"بريرا","بريرا","district",["couples","5-star"]),
 P("porta-nuova","بورتا نوفا","Porta Nuova",45.4840,9.1910,1.5,"بورتا نوفا","بورتا نوفا","district",["corporate","5-star","apartments"]),
 P("linate","مطار ليناتي","Linate Airport",45.4510,9.2760,5,"ليناتي","ليناتي","airport",["transit"]),
 P("citylife","سيتي لايف","CityLife",45.4780,9.1560,2,"سيتي لايف","سيتي لايف","district",S),
],
"vienna":[
 P("parndorf-outlet","أوتلت بارندورف","Designer Outlet Parndorf",47.9980,16.8520,10,"اوتلت بارندورف","بارندورف","landmark",S),
 P("graben","غرابن","Graben",48.2090,16.3700,1,"غرابن","غرابن","landmark",["5-star","shopping"]),
 P("westbahnhof","ويست بانهوف","Westbahnhof",48.1970,16.3380,1.5,"ويست بانهوف","ويست بانهوف","transport",["transit","budget","family"]),
 P("naschmarkt","ناش ماركت","Naschmarkt",48.1990,16.3630,1.5,"ناش ماركت","ناش ماركت","landmark",["family","budget"]),
 P("ringstrasse","الرينغ","Ringstrasse",48.2060,16.3650,1.5,"الرينغ فيينا","الرينغ","landmark",["5-star"]),
 P("akh-hospital","مستشفى AKH","AKH Vienna",48.2200,16.3470,3,"مستشفى فيينا العام","AKH","hospital",M),
],
"zurich":[
 P("foxtown-outlet","فوكس تاون أوتلت","FoxTown Mendrisio",45.8720,8.9800,10,"فوكس تاون","فوكس تاون","landmark",S),
 P("lucerne","لوسيرن","Lucerne",47.0502,8.3093,8,"لوسيرن","لوسيرن","landmark",["family","couples","nature"],kw=["فنادق لوسيرن"]),
 P("interlaken","إنترلاكن","Interlaken",46.6863,7.8632,10,"انترلاكن","إنترلاكن","landmark",["family","couples","nature"],kw=["فنادق انترلاكن"]),
 P("zurich-west","زيورخ ويست","Zurich West",47.3900,8.5180,2,"زيورخ ويست","زيورخ ويست","district",["apartments","budget"]),
 P("oerlikon","أورليكون","Oerlikon",47.4110,8.5440,2,"اورليكون","أورليكون","district",B),
],
"geneva":[
 P("montreux","مونترو","Montreux",46.4312,6.9107,8,"مونترو","مونترو","landmark",["couples","5-star","nature"],kw=["فنادق مونترو"]),
 P("lausanne","لوزان","Lausanne",46.5197,6.6323,6,"لوزان","لوزان","landmark",["family","couples"]),
 P("paquis","باكي","Paquis",46.2120,6.1490,1.5,"باكي","باكي","district",B),
 P("carouge","كاروج","Carouge",46.1820,6.1390,2,"كاروج","كاروج","district",B),
 P("hug-hospital","مستشفى جنيف الجامعي","HUG Geneva",46.1930,6.1500,3,"مستشفى جنيف","HUG","hospital",M),
],
"prague":[
 P("fashion-arena-outlet","أوتلت فاشن أرينا","Fashion Arena Outlet",50.0690,14.5750,6,"فاشن ارينا اوتلت","فاشن أرينا","landmark",S),
 P("na-prikope","نا بريكوبيه","Na Prikope",50.0860,14.4260,1,"نا بريكوبيه","نا بريكوبيه","landmark",S),
 P("mala-strana","مالا سترانا","Mala Strana",50.0880,14.4040,1,"مالا سترانا","مالا سترانا","district",["couples","5-star"]),
 P("vinohrady","فينوهرادي","Vinohrady",50.0760,14.4440,1.5,"فينوهرادي","فينوهرادي","district",["family","apartments","budget"]),
 P("petrin","بيترين","Petrin",50.0835,14.3950,1.5,"بيترين","بيترين","landmark",["family","couples"]),
],
"barcelona":[
  P("la-roca-village","لا روكا فيليدج","La Roca Village",41.6100,2.3380,8,"لا روكا فيليدج","لا روكا","landmark",S),
  P("diagonal","أفينيدا دياغونال","Avinguda Diagonal",41.3950,2.1500,1.5,"دياغونال","دياغونال","landmark",S),
  P("eixample","إيشامبلي","Eixample",41.3910,2.1640,1.5,"ايشامبلي","إيشامبلي","district",["family","apartments"]),
  P("port-olimpic","بورت أوليمبيك","Port Olimpic",41.3870,2.1980,1.5,"بورت اوليمبيك","بورت أوليمبيك","district",["beach","5-star"]),
  P("sants","محطة سانتس","Sants Station",41.3790,2.1400,1.5,"محطة سانتس","سانتس","transport",["transit","budget"]),
  P("montjuic","مونجويك","Montjuic",41.3640,2.1580,2,"مونجويك","مونجويك","landmark",["family"]),
],
"amsterdam":[
  P("de-pijp","دي بايب","De Pijp",52.3540,4.8920,1,"دي بايب","دي بايب","district",["couples","apartments"]),
  P("leidseplein","لايدسه بلاين","Leidseplein",52.3640,4.8830,1,"لايدسه بلاين","لايدسه بلاين","landmark",["family","budget"]),
  P("kalverstraat","كالفر ستراد","Kalverstraat",52.3700,4.8910,1,"كالفر ستراد","كالفر ستراد","landmark",S),
  P("amsterdam-zuid","أمستردام زاود","Amsterdam Zuid",52.3390,4.8740,2,"امستردام زاود","زاود","transport",["transit","corporate"]),
  P("zaanse-schans","زانسه سخانس","Zaanse Schans",52.4740,4.8170,6,"زانسه سخانس","زانسه سخانس","landmark",["family","nature"]),
]}
def hav(a,b):
    R=6371; p1,p2=math.radians(a["lat"]),math.radians(b["lat"]); d1=p2-p1; d2=math.radians(b["lng"]-a["lng"])
    h=math.sin(d1/2)**2+math.cos(p1)*math.cos(p2)*math.sin(d2/2)**2
    return 2*R*math.asin(math.sqrt(h))
total=0
for slug,extra in ADD.items():
    c=json.load(open(f"data/{slug}.json",encoding="utf-8"))
    have={p["slug"] for p in c["pois"]}
    c["pois"]+= [p for p in extra if p["slug"] not in have]
    for p in c["pois"]:
        others=[o for o in c["pois"] if o is not p and o["type"] not in("event","intent_hub")]
        others.sort(key=lambda o: hav(p,o))
        p["neighbours"]=[dict(slug=o["slug"],name_ar=o["name_ar"],km=round(hav(p,o),1)) for o in others[:5]]
    c["poi_count"]=len(c["pois"]); total+=len(c["pois"])
    json.dump(c,open(f"data/{slug}.json","w",encoding="utf-8"),ensure_ascii=False,indent=2)
idx=json.load(open("data/cities.json",encoding="utf-8"))
for i in idx:
    i["poi_count"]=json.load(open(f"data/{i['slug']}.json",encoding="utf-8"))["poi_count"]
json.dump(idx,open("data/cities.json","w",encoding="utf-8"),ensure_ascii=False,indent=2)
print(total,"POIs")
